--Texts
strings = {

-------------	Explorer	---------------------------------------------------------------------------------
back =			"Indietro ",
copyfile =		"Copia: ",
delfile =		"Elimina: ",
dir =			"<DIR>",
creatfolder =	"Crea una cartella",
newfolder =		"Nuova cartella",
pass =			"Utilizzare la Password ?",
ospass =		"PASS",

--SubMenu
copy =			"Copia",
delete =		"Elimina",
makedir =		"Crea una directory",
rename =		"Rinomina",
extract =		"Estrai",
cancel =		"Cancella",
insvpkfromdir = "Installa un Gioco",
instheme =		"Installa CTheme",
extractto =		"Estrai il contenuto SU",
paste =			"Incolla",
move =			"Sposta",
size =			"Formato",
scanvpks =		"Scansione dei contenuti (VPK/ISO/CSO)",
export =		"Esporta",
themes =		"Temi AppManager+",
pluginsman =	"Plugins Man",
cthemesman =	"Temi personalizzati LiveArea ",
ftp =			"FTP",
restarthb =		"Riavvia AppMan",
reset =			"Reset alimentazione",
off =			"Spegnimento",

items =			"Seleziona Elementi: ",

------------	Ftp 		---------------------------------------------------------------------------------
textftp =		"Inserire l'indirizzo FTP sul dispositivo o PC",
closeftp =		"Premere START per chiudere la connessione FTP",
loseftp =		"Connessione FTP chiusa",

------------	USB 		---------------------------------------------------------------------------------
usb =			"USB",
connectusb =	"Connettere il dispositivo con un cavo USB",
usbconnection = "Connessione USB Abilitata",
cancelusb =		"Disabilitato",

imgerror =		"Errore!! Immagine non supportata",

-- ## Music Player ##
playing =		"Riproduzione",
paused =		"Pausa",
time =			"Tempo: ",
tags =			"xx:xx:xx",
sounderror =	"Errore!! Suono non valido",

--AppManager
apptittle =		"Game Manager (Apps - Bolle)",
switch =		"Sei sicuro di voler spostare",
nomemory =		"Memoria insufficiente...",
appremove =		"Sei sicuro di voler disinstallare ",
delclon	=		"Cancella questo CLONE: ",
manual =		"Vuoi realmente eliminarlo Manualmente",
notmanual =		"Eliminazione effettuata manualmente!",
notfindmanual =	"Il Manuale non esiste",
removemanual =	"Rimuovi manuale",
pressremove =	"Disinstalla",
switchapp =		"Scambia Apps",
empty =			"Vuoto/Errore",
toexplorer =	"File Explorer",
partitions =	"Partizioni",

--SearchingVpks
vpktittle =		"Ricerca Vpks ",
wait =			"Attendere prego...",
nofinds =		"Nessun file trovato",
reloadfull =	"Scansione completa di ux0/ur0/uma0",
moveiso2ux0 =	"Gioco sposato su ux0:pspemu/ISO",
moveiso2ur0 =	"Gioco sposato su ur0:pspemu/ISO",
moveiso2uma0 =	"Gioco sposato su uma0:pspemu/ISO",

-------------		Callbacks		-------------------------------------------------------------------------
unsafe =		"Non sicuro: ",
file =			"File: ",
percent =		"Percentuale: ",
percent_total = "Percentuale Totale: ",
total_size =	"Dimensione totale: ",
total_written = "Totale Scritto: ",
speed =			"Velocità: ",
remaining =		"Tempo rimanente: ",

--onAppInstall
searchunsafe =	"Cerca nei file vpk, non sicuri o pericolosi!",
unsafevpk =		"Permessi estesi e accesso a informazioni personali richieste! \n\nUtilizzare con cautela, i pacchetti sono da sorgenti non attendibili! \n\nVuoi installare a proprio rischio?",
dangerousvpk =	"Attenzione!!! Elevato rischio di brick del dispositivo se questo VPK è installato! \n\nUtilizzare con cautela, i pacchetti sono da sorgenti non attendibili! \n\nVuoi installare a proprio rischio?",
vpkunpack =		"Scompattamento vpk in corso...",
install =		"Installazione in corso...",

--onExtractFiles
extraction =	"Estrazione in corso...",

--onScanningFiles
scanning =		"Scansione in corso...",
size_unpk =		"Dimensione del file scompattato: ",
-------------------------------------------------------------------------------------------------------------

--Launch PBP or VPK
launchpbp =		"Avvia gioco/app ",
confirm =		"Accetta",
warningvpk =	"\nPERICOLO ACCESSO TOTALE\nVPK NON SICURO",
warningvpk2 =	"PERICOLO ACCESSO TOTALE",
safevpk =		"VPK SICURO",
total_sizevpk = "Dimensione totale VPK: ",
installvpk =	"INSTALLA VPK",
installgame =	"INSTALLA APP",
alertunsafe =	"VPK NON SICURO!!!!",
alertdang =		"VPK PERICOLOSO!!!!",
installvpkdir =	"INSTALLA VPK DA DIRECTORY",
launchbin =		"Avvia app ",

------------	Switch Apps/vpks	-------------------------------------------------------------------------
required =		"\nRichiesto: ",
searchapp =		"\nDesideri spostare un app per su ur0 ?",
vpktour0 =		"Desideri spostare il file vpk su ur0: per poterlo installare ?",
vpktoux0 =		"Desideri spostare il file vpk su ux0: ?",
stillnomemory =	"Non c'è spazio sufficiente anche se viene spostato",
vpkinuro =		"Il file vpk è già su ur0:...\nProva a liberare un po' di spazio...",
apptour0 =		"Passa su ur0:",
ur0toapp =		"Passare l' app su ux0: ?",
tittle =		"Titolo: ",
errorapp =		"Errore...l'app non puo' essere spostata...",
errorinstall =	"Si è verificato un errore durante l'installazione",

------------	ThemesAppmanager	-------------------------------------------------------------------------
themesappman =	"Temi per AppManager PLUS",
themesdone =	"Installazione Completata!",
reload =		"Ricarica il Tema Originale",
settinsthemes =	"Andare su Impostazioni Tema ?",

------------	PluginsManager		-------------------------------------------------------------------------
plugsmanager =	"Plugins Manager",
reloadconfig =	"TaiHen Config",
configtxt =		"Ricaricare taiHEN ConfigTxt",
disablesuprx =	"Disabilitare il plugin ?",

------------	ThemesLivearea		-------------------------------------------------------------------------
customthemes =	"CustomThemes LiveArea",
notthemes =		"Vuoto/Errore nell'elenco dei temi!",
deltheme =		"Disinstalla CustomTheme da app.db",
delfilestheme =	"Cancellare i file da CustomTheme ?",

------------	Advanced	---------------------------------------------------------------------------------
advanced =		"Avanzato",
refreshdb =		"Aggiorna app.db",
rebuilddb =		"Ricostruisci app.db",
restartupdb =	"La tua PSVita sarà riavviata...\ny Il database verrà aggiornato",
restartredb =	"La tua PSVita sarà riavviata...\nY Il database verrà ricostruito",
restart =		"La tua PSVita sarà riavviata...",
shutdown =		"La tua PSVita sarà spenta...",

result =		"\nRisultato: ",
count =			"Conteggio: ",
sizeis =		"La dimensione è: ",
opensettings =	"Aprire Mp3 Player/Gallery/Video ?",
filesfolders =	"File/Cartelle",

}
